# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Y8nr1lceXiS6660INU--x8YrtHdUq7h
"""

import numpy as np
from scipy.stats import bernoulli

sample_size=100000

prob_A=0.2
prob_AB=0.15
prob_B_only=0.15

#Simulations using Bernoulli r.v.
sample_A= bernoulli.rvs(size= sample_size, p = prob_A)
sample_AB= bernoulli.rvs(size= sample_size, p = prob_AB)
sample_B_only= bernoulli.rvs(size= sample_size, p= prob_B_only)


#calculating P(A-B):

quant_A= np.nonzero(sample_A==1)
quant_AB= np.nonzero(sample_AB==1)       
#finding probability of A-B
prob_A_only= (np.size(quant_A)/sample_size)-(np.size(quant_AB)/sample_size)        
print("P(A-B) = ", prob_A_only)
print("which is approximately equal to 0.05(theoritical value)")

#calculating P(B):

        
quant_B_only= np.nonzero(sample_B_only==1)
quant_AB= np.nonzero(sample_AB==1)       
#finding probability B
prob_B= (np.size(quant_B_only)/sample_size) + (np.size(quant_AB)/sample_size)        
print("P(B) = ", prob_B)

print("which is approximately equal to 0.30(theoritical value)")
#calculating P(A|B):
prob_A_B=prob_AB/prob_B       
print("P(A|B) = ", prob_A_B)

print("which is approximately equal to 0.50(theoritical value)")
