# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kBLfly8PqYaWGcCXMtWDeNYqEV74Bv5g
"""

import numpy as np
#given values
Prob_A_fails=0.2 
Prob_B_fails_only=0.15
Prob_A_and_B_fails=0.15

Prob_A_fails_only = Prob_A_fails - Prob_A_and_B_fails
Prob_B_fails=Prob_B_fails_only+ Prob_A_and_B_fails
Prob_A_fails_B_had_failed= Prob_A_and_B_fails/Prob_B_fails

print("Probability of A fails such that B already failed is:",Prob_A_fails_B_had_failed)
print("Probability of A fails only is:",Prob_A_fails_only)